# conda env export --no-builds | grep -v "prefix" > environment.yml
#
# Quick way to get started!
# conda env create -f environment.yml
name: FairMOT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.7.0
  - torchvision=0.8.0
  - cudatoolkit=10.2
  - opencv
  - pip:
    - yacs
    - opencv-python
    - PyYAML
    - cython-bbox
    - scipy
    - progress
    - motmetrics
    - matplotlib
    - lap
    - openpyxl
    - Pillow
    - tensorboardX
    - fvcore
