# conda env export --no-builds | grep -v "prefix" > environment.yml
#
# Quick way to get started!
# conda env create -f environment.yml
name: FairMOT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.1
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - cachetools=4.2.2
  - certifi=2022.6.15
  - click=8.0.4
  - cryptography=37.0.1
  - cudatoolkit=10.2.89
  - dataclasses=0.8
  - debugpy=1.6.0
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - freetype=2.11.0
  - giflib=5.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.15.1
  - ipython=8.4.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.0.6
  - jupyter_core=4.11.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.22.3
  - numpy-base=1.22.3
  - oauthlib=3.1.0
  - openssl=1.1.1q
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - prompt-toolkit=3.0.30
  - psutil=5.9.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.12.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.7.0
  - pyzmq=19.0.2
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - stack_data=0.3.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.12
  - torchvision=0.8.0
  - tornado=6.1
  - traitlets=5.3.0
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - wcwidth=0.2.5
  - werkzeug=2.0.3
  - wheel=0.37.1
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astroid==2.11.7
    - autopep8==1.6.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - cloudpickle==2.1.0
    - cycler==0.11.0
    - cython==0.29.30
    - cython-bbox==0.1.3
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - distlib==0.3.5
    - dm-tree==0.1.7
    - et-xmlfile==1.1.0
    - fastjsonschema==2.16.1
    - filelock==3.7.1
    - flake8==4.0.1
    - fonttools==4.34.4
    - frozenlist==1.3.0
    - fvcore==0.1.5.post20220512
    - gputil==1.4.0
    - grpcio==1.43.0
    - gym==0.21.0
    - imageio==2.19.5
    - importlib-resources==5.8.0
    - iopath==0.1.10
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - isort==5.10.1
    - jinja2==3.1.2
    - jsonschema==4.7.2
    - jupyter==1.0.0
    - jupyter-console==6.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.1
    - kiwisolver==1.4.4
    - lap==0.4.0
    - lazy-object-proxy==1.7.1
    - lz4==4.0.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mccabe==0.6.1
    - mistune==0.8.4
    - motmetrics==1.2.5
    - msgpack==1.0.4
    - mypy==0.971
    - mypy-extensions==0.4.3
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - networkx==2.8.5
    - notebook==6.4.12
    - opencv-python==4.6.0.66
    - openpyxl==3.0.10
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - platformdirs==2.5.2
    - portalocker==2.5.1
    - progress==1.6
    - prometheus-client==0.14.1
    - protobuf==3.20.1
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - pylint==2.14.5
    - pyrsistent==0.18.1
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qtconsole==5.3.1
    - qtpy==2.1.0
    - ray==1.13.0
    - scikit-image==0.19.3
    - scipy==1.8.1
    - send2trash==1.8.0
    - snakeviz==2.1.1
    - soupsieve==2.3.2.post1
    - tabulate==0.8.10
    - tensorboardx==2.5.1
    - termcolor==1.1.0
    - terminado==0.15.0
    - tifffile==2022.5.4
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.1
    - tqdm==4.64.0
    - urllib3==1.26.10
    - virtualenv==20.15.1
    - webencodings==0.5.1
    - widgetsnbextension==3.6.1
    - wrapt==1.14.1
    - xmltodict==0.13.0
    - yacs==0.1.8
    - zipp==3.8.1
